export const SET_BOOKS="SET_BOOKS"
export const SET_CHARACTERS="SET_CHARACTERS"
export const SET_MOVIES="SET_MOVIES"
export const SET_QUOTES="SET_QUOTES"
export const SET_CHARACTER_FILTER="SET_CHARACTER_FILTER"
export const SET_MOVIE_FILTER="SET_MOVIE_FILTER"

